# Generated by Django 3.1.7 on 2021-03-17 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0002_auto_20210312_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='no description available'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quote',
            field=models.TextField(default='no quote available'),
        ),
    ]
