# Generated by Django 3.1.7 on 2021-03-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20210317_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='books',
        ),
    ]
