# Generated by Django 3.1.7 on 2021-03-17 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0005_auto_20210317_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bookincart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
